### ISSUE TITLE
Login error

### ISSUE THREAD

**Issue by wjrmffldrhrl** [kyu9341/TeamHash#12]
# Error
master branch에서 로그인 기능을 추가하기 위해 login branch를 만들어 작업을 하던 중

로그인 과정을 어느정도 이해한 뒤 구현을 성공했다고 생각했으나, 디비에 존재하는 계정값을 넣어도 로그인이 되지 않는 문제가 발생했습니다.

https://github.com/kyu9341/TeamHash/tree/login

# templates
## login.html
~~~html
<form th:action="@{/login}" method="POST">
      <h1 th:if="${param.error}">
        Invalid username and password.
      </h1>
      <div class="group">
        <input type="username" class="used"><span class="highlight"></span><span class="bar"></span>
        <label>Username</label>
      </div>
      <div class="group">
        <input type="password"><span class="highlight"></span><span class="bar"></span>
        <label>Password</label>
      </div>

      <button type="submit" class="buttonui"> <span> login </span>
            <div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
      </button>

      <button type="button" class="buttonui" onclick="location.href='/sign-up'"> <span> sign up </span>
        <div class="ripples buttonRipples"> <span class="ripplesCircle"></span></div>
      </button>

    </form>
~~~
로그인이 진행되는 폼입니다. email과 password를 넣고 /login action을 통해 로그인을 진행합니다.  

입력된 정보가 없어서 로그인이 실패할 시 Invalid username and password 메세지가 나옵니다.  

## main.html
~~~html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:th="https://www.thymeleaf.org"
      xmlns:sec="https://www.thymeleaf.org/thymeleaf-extras-springsecurity3">
    <head>
        <title>Hello World!</title>
    </head>
    <body>
        <h1 th:inline="text">Hello [[${#httpServletRequest.remoteUser}]]!</h1>
        <form th:action="@{/logout}" method="post">
            <input type="submit" value="Sign Out"/>
        </form>
    </body>
</html>
~~~
로그인 성공시 호출되는 페이지 입니다. 로그인된 유저의 정보를 확인하고 싶었습니다.
# Domain
## Account.java
~~~java
package kr.co.teamhash.domain;

import lombok.*;

import javax.persistence.*;
import java.time.LocalDateTime;

@Entity
@Getter @Setter @EqualsAndHashCode(of = "id")
@Builder @AllArgsConstructor @NoArgsConstructor
public class Account {

    @Id @GeneratedValue
    private Long id;

    @Column(unique = true)
    private String email;

    @Column(unique = true)
    private String nickname;

    private String password;

    private String school;

    private boolean emailVerified;

    private String emailCheckToken;

    private LocalDateTime joinedAt;

    private String introduction;


    @Lob @Basic(fetch = FetchType.EAGER)
    private String profileImage;

}
~~~

## SecurityAccount.java
~~~java
package kr.co.teamhash.domain;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;

public class SecurityAccount extends User {


    private static final long serialVersionUID = 1L;
    
    public SecurityAccount(Account account) {
        super(account.getNickname(),account.getPassword(), null);
        // TODO Auto-generated constructor stub
    }
}
~~~
Spring Security에서 제공하는 사용자 Interface UserDetails를 상속받기 위해 SecurityAccount 클래스를 구현했습니다.  
접근권한이 필요 없다고 생각되어 생성자에 null을 넣었습니다.
## AccountRepository.java

~~~java
package kr.co.teamhash.account;

import kr.co.teamhash.domain.Account;

import java.util.Optional;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.transaction.annotation.Transactional;

@Transactional(readOnly = true)
public interface AccountRepository extends JpaRepository<Account, Long> {
    boolean existsByEmail(String email);

    boolean existsByNickname(String nickname);

    Account findByEmail(String email);//로그인 시 email을 통해 유저 정보를 가져옴
}
~~~
회원가입시 중복 처리를 막기위한 메서드와 로그인할 때 email로 회원 정보를 가져오기 위한 findByEmail 메서드가 구현되어있습니다.

# Config
## SecurityConfig.java
~~~java
package kr.co.teamhash.config;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.autoconfigure.security.servlet.PathRequest;

import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;


@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {


    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .mvcMatchers("/", "/sign-up", "/check-email-token").permitAll() // 인증 허가
                .anyRequest().authenticated()
                .and()
            .formLogin()// 로그인 폼 사용
                .defaultSuccessUrl("/main") // 로그인 성공시 main 호출
                .loginPage("/login")
                .permitAll()
                .and()
            .logout()
                .permitAll();
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations());
        // 스태틱 리소스들은 시큐리티 적용 x
    }


}

~~~
WebSecurityConfigurerAdapter를 구현한 SecurityConfig입니다. 인증 페이지를 관리한다고 이해하고있습니다.

기존에 있던 코드에서 loginPage를 추가하였습니다. 

# UserDetailsService
## UserDetailsServiceImpl.java
~~~java
package kr.co.teamhash.account;

import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import kr.co.teamhash.domain.Account;
import kr.co.teamhash.domain.SecurityAccount;
import lombok.RequiredArgsConstructor;

//유저 정보 인증에 사용되는 UserDetailsService 구현
@Service
@RequiredArgsConstructor
public class UserDetailsServiceImpl implements UserDetailsService {
    
    
    AccountRepository accountRepository;


    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        
        // TODO Auto-generated method stub
        

        Account account = accountRepository.findByEmail(email);
                //.orElseThrow(() -> new UsernameNotFoundException(email));

        if(account == null)
            throw new UsernameNotFoundException(email);
        
        return new SecurityAccount(account);
    }

}
~~~  
로그인시 유저 정보를 비교하는 클래스라고 이해하고 있습니다.  

User클래스를 확장시킨 SecurityAccount객체를 반환하고 있습니다.  

# 결과
![image](https://user-images.githubusercontent.com/49122299/80276932-abdb3b80-8726-11ea-8990-55575f8788f3.png)
회원가입을 통해 입력된 회원 정보입니다.

![image](https://user-images.githubusercontent.com/49122299/80276944-c3b2bf80-8726-11ea-9d0e-2f1f05cef135.png)

id : test@naver.com 
password : testtest
위의 정보로 로그인을 진행해 보겠습니다.

![image](https://user-images.githubusercontent.com/49122299/80276967-e513ab80-8726-11ea-9c85-e115fc6d87fd.png)
로그인 실패시 입력되는 파라미터 값을 받고 error 메세지를 띄웁니다.

제가 빠트린 부분이나 잘못 이해한부분을 알고 싶습니다.

**Comment by kyu9341** [comment]
-`SecurityAccount.java` 를 다음과 같이 변경해보시기 바랍니다.
```java
package kr.co.teamhash.domain;

import java.util.Collection;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;

public class SecurityAccount extends User {


    private static final long serialVersionUID = 1L;
    private Account account;

    public SecurityAccount(Account account) {
        super(account.getNickname(),account.getPassword(), List.of(new SimpleGrantedAuthority("ROLE_USER")));
        this.account = account;
}
```

**Comment by wjrmffldrhrl** [comment]
권한을 아래와 같이 생성한 뒤 추가하였습니다.

`Role.java`
~~~java

import lombok.AllArgsConstructor;
import lombok.Getter;

//권한 설정을 위한 Enum
@AllArgsConstructor
@Getter
public enum Role {

    MEMBER("ROLE_MEMBER"),
    ADMIN("ROLE_ADMIN");

    private String value;

}
~~~

`SecurityAccount.java`
~~~java
package kr.co.teamhash.domain.entity;

import java.util.Collection;
import java.util.List;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.userdetails.User;

public class SecurityAccount extends User {


    private static final long serialVersionUID = 1L;
 
    

    public SecurityAccount(Account account, Collection<? extends GrantedAuthority> authorities) {
        super(account.getEmail(),account.getPassword(), authorities);
    }
}
~~~

`UserDetailsServiceImpl.java`
~~~java
package kr.co.teamhash.account;

import java.util.HashSet;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import kr.co.teamhash.domain.entity.Account;
import kr.co.teamhash.domain.entity.Role;
import kr.co.teamhash.domain.entity.SecurityAccount;
import kr.co.teamhash.domain.repository.AccountRepository;
import lombok.RequiredArgsConstructor;

//유저 정보 인증에 사용되는 UserDetailsService 구현
@Service
@RequiredArgsConstructor
public class UserDetailsServiceImpl implements UserDetailsService {
    
    
    AccountRepository accountRepository;


    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        
        // TODO Auto-generated method stub
        

        Account account = accountRepository.findByEmail(email)
                .orElseThrow(() -> new UsernameNotFoundException(email));

        Set<GrantedAuthority> grantedAuthorities = new HashSet<>();

        grantedAuthorities.add(new SimpleGrantedAuthority(Role.MEMBER.getValue()));//권한 추가
        
        
        return new SecurityAccount(account,grantedAuthorities);
    }

    
}
~~~

**Comment by wjrmffldrhrl** [comment]
`SecurityConfig.java` 에서 오류가 발생하기 시작했습니다. 

~~~java
package kr.co.teamhash.config;

import org.springframework.boot.autoconfigure.security.servlet.PathRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;



@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {


    UserDetailsService userDetailsService;
    
    @Bean// 비밀번호 암호화
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .mvcMatchers("/", "/sign-up", "/check-email-token").permitAll() // 인증 허가
                .anyRequest().authenticated()
                .and()
            .formLogin()// 로그인 폼 사용
                .defaultSuccessUrl("/main") // 로그인 성공시 main 호출
                .loginPage("/login")
                .permitAll()
                .and()
            .logout()
                .permitAll();
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations());
        // 스태틱 리소스들은 시큐리티 적용 x
    }

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception { // 해당 메서드를 주석처리하면 오류가  나지 않습니다.
        auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
    }

}

~~~

오류 전문입니다.
~~~
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:322) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
WebSecurityConfigurerAdapter.java:322
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter.init(WebSecurityConfigurerAdapter.java:92) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
WebSecurityConfigurerAdapter.java:92
	at kr.co.teamhash.config.SecurityConfig$$EnhancerBySpringCGLIB$$266de9eb.init(<generated>) ~[classes/:na]
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.init(AbstractConfiguredSecurityBuilder.java:370) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
AbstractConfiguredSecurityBuilder.java:370
	at org.springframework.security.config.annotation.AbstractConfiguredSecurityBuilder.doBuild(AbstractConfiguredSecurityBuilder.java:324) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
AbstractConfiguredSecurityBuilder.java:324
	at org.springframework.security.config.annotation.AbstractSecurityBuilder.build(AbstractSecurityBuilder.java:41) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
AbstractSecurityBuilder.java:41
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration.springSecurityFilterChain(WebSecurityConfiguration.java:104) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
WebSecurityConfiguration.java:104
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
SimpleInstantiationStrategy.java:154
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.security.authentication.dao.DaoAuthenticationProvider@5ee9f575': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException: A UserDetailsService must be set
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
AbstractAutowireCapableBeanFactory.java:1796
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:407) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
AbstractAutowireCapableBeanFactory.java:407
	at org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor.postProcess(AutowireBeanFactoryObjectPostProcessor.java:67) ~[spring-security-config-5.2.2.RELEASE.jar:5.2.2.RELEASE]
AutowireBeanFactoryObjectPostProcessor.java:67
	... 49 common frames omitted
Caused by: java.lang.IllegalArgumentException: A UserDetailsService must be set
	at org.springframework.util.Assert.notNull(Assert.java:198) ~[spring-core-5.2.5.RELEASE.jar:5.2.5.RELEASE]
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.doAfterPropertiesSet(DaoAuthenticationProvider.java:100) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
DaoAuthenticationProvider.java:100
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.afterPropertiesSet(AbstractUserDetailsAuthenticationProvider.java:123) ~[spring-security-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
AbstractUserDetailsAuthenticationProvider.java:123
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
AbstractAutowireCapableBeanFactory.java:1855
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.5.RELEASE.jar:5.2.5.RELEASE]
AbstractAutowireCapableBeanFactory.java:1792
	... 51 common frames omitted
~~~

**Comment by wjrmffldrhrl** [comment]
해당 오류는 `AuthenticationManagerBuilder` 에서 발생하는 것으로 확인되었습니다.
~~~java
    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception { 
        auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
    }
~~~
이때 `userDetailsService`를 주입할 때 생성한 `userDetailsService`에 문제가 있었습니다.  

~~~java
package kr.co.teamhash.account;

import java.util.HashSet;
import java.util.Set;

import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import kr.co.teamhash.domain.entity.Account;
import kr.co.teamhash.domain.entity.Role;
import kr.co.teamhash.domain.entity.SecurityAccount;
import kr.co.teamhash.domain.repository.AccountRepository;
import lombok.RequiredArgsConstructor;

//유저 정보 인증에 사용되는 UserDetailsService 구현
@Service
@RequiredArgsConstructor
public class UserDetailsServiceImpl implements UserDetailsService {
    
    
    AccountRepository accountRepository; //회원 정보를 조회할 repository 생성

    public UserDetailsServiceImpl(AccountRepository accountRepository){
        this.accountRepository = accountRepository;
    }

    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        
        // TODO Auto-generated method stub
        

        Account account = accountRepository.findByEmail(email)
                .orElseThrow(() -> new UsernameNotFoundException(email));

        Set<GrantedAuthority> grantedAuthorities = new HashSet<>();

        grantedAuthorities.add(new SimpleGrantedAuthority(Role.MEMBER.getValue()));
        
        
        return new SecurityAccount(account,grantedAuthorities);
        
    }
}
~~~  
`UserDetailsServiceImpl` 내부 변수에 repository를 넣고 이후 `SecurityConfig` 에서 `configure`메서드를 오버라이드 할 때 새로운 객체를 생성한 뒤 repository를 넣어주는 방식으로 수정했습니다.  

~~~java
package kr.co.teamhash.config;


import org.springframework.boot.autoconfigure.security.servlet.PathRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;

import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import kr.co.teamhash.account.UserDetailsServiceImpl;
import kr.co.teamhash.domain.repository.AccountRepository;



@Configuration
@EnableWebSecurity
public class SecurityConfig extends WebSecurityConfigurerAdapter {



    AccountRepository accountrepository; // userDetailsService에 사용될 repository

    @Bean// 비밀번호 암호화
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .mvcMatchers("/","/sign-up", "/check-email-token").permitAll() // 인증 허가
                .anyRequest().authenticated()
                .and()
            .formLogin()// 로그인 폼 사용
                .defaultSuccessUrl("/main") // 로그인 성공시 main 호출
                .loginPage("/login")
                .permitAll()
                .and()
            .logout()
                .permitAll();
        
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations());
        // 스태틱 리소스들은 시큐리티 적용 x
    }

    // @Override
    // public void configure(AuthenticationManagerBuilder auth) throws Exception {
    //     auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
    // }

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {//사용자 정보 비교
        auth.userDetailsService(new UserDetailsServiceImpl(accountrepository)).passwordEncoder(passwordEncoder());
       // auth.inMemoryAuthentication().withUser("test4@naver.com").password("testtest").roles("MEMBER");
        
    }

}
~~~ 

이후 어플리케이션이 실행 후 바로 종료되는 문제는 해결됐지만 일치하는 유저 정보를 입력해도 로그인이 진행되지 않는 문제가 남아있습니다.

**Comment by wjrmffldrhrl** [comment]
![image](https://user-images.githubusercontent.com/49122299/80297859-0d9cb380-87c2-11ea-8360-a847962b2155.png)
실행 로그를 확인하니 `loadUserByUsername` 메서드에 email이 전달되지 않는것을 확인했습니다. 그래서 null 오류가 발생한 것으로 확인됩니다.

**Comment by wjrmffldrhrl** [comment]
![image](https://user-images.githubusercontent.com/49122299/80298268-6c176100-87c5-11ea-97b8-27e91ad52266.png)
email이 전달됐다는 가정하에 진행상황을 살펴보기 위해 email을 직접 입력하고 디버깅을 해보았지만 
~~~java
Account account = accountRepository.findByEmail(email)
                .orElseThrow(() -> new UsernameNotFoundException("no user"));
~~~
repository에서 email로 유저의 정보를 가져오는 과정에서 아래와 같은 오류가 발생했습니다.

`org.springframework.security.authentication.InternalAuthenticationServiceException: null`

**Comment by wjrmffldrhrl** [comment]
email이 전달되지 않는 이유는 로그인폼에서 input의 name속성이 없어서 발생한 문제였습니다.

## login.html
~~~html
 <form th:action="@{/login}" method="POST">
      <h1 th:if="${param.error}">
        Invalid username and password.
      </h1>
      <div class="group">
        <input type="username" class="used" name="username"><span class="highlight"></span><span class="bar"></span>
        <label>Username</label>
      </div>
      <div class="group">
        <input type="password" name="password"><span class="highlight"></span><span class="bar"></span>
        <label>Password</label>
      </div>

      <button type="submit" class="buttonui"> <span> login </span>
            <div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
      </button>

      <button type="button" class="buttonui" onclick="location.href='/sign-up'"> <span> sign up </span>
        <div class="ripples buttonRipples"> <span class="ripplesCircle"></span></div>
      </button>

    </form>
~~~

그러나 직접 입력하고 디버깅할 때 처럼 동일한 오류가 발생합니다.

**Comment by wjrmffldrhrl** [comment]
repository에 접근에 문제가 있는지 확인하기 위해 기존에 구현해 둔 메서드인 `existsByNickname`를 호출해봤습니다.

![image](https://user-images.githubusercontent.com/49122299/80299963-a851be00-87d3-11ea-8334-728c8e59bbf7.png)
동일한 오류가 발생하였고 이에 저는 repository에 접근이 되지 않는다는 것을 알았습니다.  

repository가 정상적으로 작동되고있는 `SignUpValidator.java`를 보니 repository가 private final로 생성되어 있었습니다.   

## SignUpValidator.java  

~~~java
package kr.co.teamhash.account;

import kr.co.teamhash.domain.entity.Account;
import kr.co.teamhash.domain.repository.AccountRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Component;
import org.springframework.validation.Errors;
import org.springframework.validation.Validator;

@Component
@RequiredArgsConstructor // lombok이 제공하는 어노테이션, private final 타입의 맴버 변수의 생성자를 만들어준다.
public class SignUpValidator implements Validator {

    private final AccountRepository accountRepository;

    @Override
    public boolean supports(Class<?> clazz) {
        // SignUpForm 타입의 인스턴스를 검사
        return clazz.isAssignableFrom(SignUpForm.class);
    }

    @Override
    public void validate(Object target, Errors errors) {
        // 이메일, 닉네임 중복 검사
        SignUpForm signUpForm = (SignUpForm)target;
        if(accountRepository.existsByEmail(signUpForm.getEmail())){
            errors.rejectValue("email", "invalid.email",
                    new Object[]{signUpForm.getEmail()}, "이미 사용중인 이메일입니다.");
        }

        if(accountRepository.existsByNickname(signUpForm.getNickname())){
            errors.rejectValue("nickname", "invalid.nickname",
                    new Object[]{signUpForm.getNickname()}, "이미 사용중인 닉네임입니다..");
        }

    }
}
~~~  

## UserDetailsServiceImpl.java & SecurityConfig.java
동일한 환경을 구성하기 위해 `UserDetailsServiceImpl`와 해당 클래스를 호출하는 `SecurityConfig`클래스에서 repository를 private final로 생성하였습니다.  
~~~java
package kr.co.teamhash.account;

import java.util.HashSet;
import java.util.Set;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.userdetails.UserDetails;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.security.core.userdetails.UsernameNotFoundException;
import org.springframework.stereotype.Service;

import kr.co.teamhash.domain.entity.Account;
import kr.co.teamhash.domain.entity.Role;
import kr.co.teamhash.domain.entity.SecurityAccount;
import kr.co.teamhash.domain.repository.AccountRepository;
import lombok.RequiredArgsConstructor;

//유저 정보 인증에 사용되는 UserDetailsService 구현
@Service
public class UserDetailsServiceImpl implements UserDetailsService {
    
    @Autowired
    private final AccountRepository accountRepository; //회원 정보를 조회할 repository 생성

    public UserDetailsServiceImpl(AccountRepository accountRepository){
        this.accountRepository = accountRepository;
    }

    @Override
    public UserDetails loadUserByUsername(String email) throws UsernameNotFoundException {
        System.out.println("-----------------------------------");
        System.out.println("find user :"+email);
        System.out.println("-----------------------------------");
       
   

        // Account account = accountRepository.findByEmail(email)
        //         .orElseThrow(() -> new UsernameNotFoundException("no user"));
       
        System.out.println("-----------------------------------");
        System.out.println("find user :"+accountRepository.existsByEmail(email));
        System.out.println("-----------------------------------");


        Account account = accountRepository.findByEmail(email);
        if(account == null){
            throw new UsernameNotFoundException("not found "+email);
        }
        String password = account.getPassword();

       System.out.println("-----------------------------------");
       System.out.println("user password:");
       System.out.println("-----------------------------------");
      
        // Account account = new Account();
        // account.setEmail("test@naver.com");
        // account.setPassword("$2a$10$pCWLKrq267sajhKzO0nbTelSVYof4a9gtifAkelLIizEtgiHeYJUC");
        Set<GrantedAuthority> grantedAuthorities = new HashSet<>();

        grantedAuthorities.add(new SimpleGrantedAuthority(Role.MEMBER.getValue()));
        
        
        return new SecurityAccount(account,grantedAuthorities);
        
    }

    
}
~~~
~~~java
package kr.co.teamhash.config;

import org.springframework.boot.autoconfigure.security.servlet.PathRequest;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.authentication.builders.AuthenticationManagerBuilder;

import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.builders.WebSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter;

import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.security.crypto.password.PasswordEncoder;

import kr.co.teamhash.account.UserDetailsServiceImpl;
import kr.co.teamhash.domain.repository.AccountRepository;
import lombok.RequiredArgsConstructor;



@Configuration
@EnableWebSecurity
@RequiredArgsConstructor 
public class SecurityConfig extends WebSecurityConfigurerAdapter {



    private final AccountRepository accountrepository; // userDetailsService에 사용될 repository

    @Bean// 비밀번호 암호화
    public PasswordEncoder passwordEncoder() {
        return new BCryptPasswordEncoder();
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http.authorizeRequests()
                .mvcMatchers("/","/sign-up", "/check-email-token").permitAll() // 인증 허가
                .anyRequest().authenticated()
                .and()
            .formLogin()// 로그인 폼 사용
                .defaultSuccessUrl("/main") // 로그인 성공시 main 호출
                .loginPage("/login")
                .usernameParameter("email") // username 파라미터 설정
                .permitAll()
                .and()
            .logout()
                .permitAll();
        
    }

    @Override
    public void configure(WebSecurity web) throws Exception {
        web.ignoring()
                .requestMatchers(PathRequest.toStaticResources().atCommonLocations());
        // 스태틱 리소스들은 시큐리티 적용 x
    }

    // @Override
    // public void configure(AuthenticationManagerBuilder auth) throws Exception {
    //     auth.userDetailsService(userDetailsService).passwordEncoder(passwordEncoder());
    // }

    @Override
    public void configure(AuthenticationManagerBuilder auth) throws Exception {//사용자 정보 비교
        auth.userDetailsService(new UserDetailsServiceImpl(accountrepository)).passwordEncoder(passwordEncoder());
       // auth.inMemoryAuthentication().withUser("test4@naver.com").password("testtest").roles("MEMBER");
        
    }

}

~~~
이후 동작시켜보니 잘 동작하며 로그인 한 뒤 로그인한 유저가 어떤 유저인지 파악 가능하였습니다.

## 결과
![image](https://user-images.githubusercontent.com/49122299/80300072-67a67480-87d4-11ea-9262-e22c4ba92536.png)

![image](https://user-images.githubusercontent.com/49122299/80300077-742acd00-87d4-11ea-8601-153c31999623.png)
